//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orc.LogViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orc.LogViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string LogViewer_AdvancedLogViewerControl_Button_Content_Clear {
            get {
                return ResourceManager.GetString("LogViewer_AdvancedLogViewerControl_Button_Content_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string LogViewer_AdvancedLogViewerControl_Button_Content_Copy {
            get {
                return ResourceManager.GetString("LogViewer_AdvancedLogViewerControl_Button_Content_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string LogViewer_AdvancedLogViewerControl_Button_Content_Open {
            get {
                return ResourceManager.GetString("LogViewer_AdvancedLogViewerControl_Button_Content_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit filter groups.
        /// </summary>
        internal static string LogViewer_AdvancedLogViewerControl_EditFilterGroups_Button_ToolTip {
            get {
                return ResourceManager.GetString("LogViewer_AdvancedLogViewerControl_EditFilterGroups_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter group editor.
        /// </summary>
        internal static string LogViewer_AdvancedLogViewerControl_Editor_Title {
            get {
                return ResourceManager.GetString("LogViewer_AdvancedLogViewerControl_Editor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string LogViewer_AdvancedLogViewerControl_FilterBoxControl_Watermark_Filter {
            get {
                return ResourceManager.GetString("LogViewer_AdvancedLogViewerControl_FilterBoxControl_Watermark_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string LogViewer_AdvancedLogViewerControl_None {
            get {
                return ResourceManager.GetString("LogViewer_AdvancedLogViewerControl_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show timestamps.
        /// </summary>
        internal static string LogViewer_AdvancedLogViewerControl_ShowTimestamps {
            get {
                return ResourceManager.GetString("LogViewer_AdvancedLogViewerControl_ShowTimestamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string LogViewer_AdvancedLogViewerControl_TextBlock_Text_Debug {
            get {
                return ResourceManager.GetString("LogViewer_AdvancedLogViewerControl_TextBlock_Text_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string LogViewer_AdvancedLogViewerControl_TextBlock_Text_Error {
            get {
                return ResourceManager.GetString("LogViewer_AdvancedLogViewerControl_TextBlock_Text_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string LogViewer_AdvancedLogViewerControl_TextBlock_Text_Info {
            get {
                return ResourceManager.GetString("LogViewer_AdvancedLogViewerControl_TextBlock_Text_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string LogViewer_AdvancedLogViewerControl_TextBlock_Text_Warning {
            get {
                return ResourceManager.GetString("LogViewer_AdvancedLogViewerControl_TextBlock_Text_Warning", resourceCulture);
            }
        }
    }
}
